local M = {}

M.base_30 = {
  white = "#fafafa",
  darker_black = "#080808",
  black = "#0d0d0d",
  black2 = "#141414",
  one_bg = "#1a1a1a",
  one_bg2 = "#222222",
  one_bg3 = "#2a2a2a",
  grey = "#4a4a4a",
  grey_fg = "#5a5a5a",
  grey_fg2 = "#6a6a6a",
  light_grey = "#8a8a8a",
  red = "#ff6b6b",
  baby_pink = "#ff8787",
  pink = "#f06595",
  line = "#1a1a1a",
  green = "#51cf66",
  vibrant_green = "#40c057",
  nord_blue = "#5c7cfa",
  blue = "#4dabf7",
  yellow = "#fcc419",
  sun = "#ffe066",
  purple = "#be4bdb",
  dark_purple = "#9c36b5",
  teal = "#20c997",
  orange = "#d97756",
  cyan = "#22b8cf",
  statusline_bg = "#101010",
  lightbg = "#1e1e1e",
  pmenu_bg = "#d97756",
  folder_bg = "#5c7cfa",
}

M.base_16 = {
  base00 = "#0d0d0d",
  base01 = "#141414",
  base02 = "#222222",
  base03 = "#4a4a4a",
  base04 = "#6a6a6a",
  base05 = "#e8e8e8",
  base06 = "#f0f0f0",
  base07 = "#fafafa",
  base08 = "#ff6b6b",
  base09 = "#d97756",
  base0A = "#fcc419",
  base0B = "#51cf66",
  base0C = "#20c997",
  base0D = "#4dabf7",
  base0E = "#be4bdb",
  base0F = "#d97756",
}

M.polish_hl = {
  treesitter = {
    ["@variable"] = { fg = M.base_16.base05 },
    ["@variable.builtin"] = { fg = M.base_30.red },
    ["@variable.parameter"] = { fg = "#e8a87c" },
    ["@constant"] = { fg = M.base_30.orange },
    ["@constant.builtin"] = { fg = M.base_30.orange },
    ["@string"] = { fg = M.base_30.green },
    ["@string.escape"] = { fg = M.base_30.cyan },
    ["@character"] = { fg = M.base_30.green },
    ["@number"] = { fg = M.base_30.orange },
    ["@boolean"] = { fg = M.base_30.orange },
    ["@float"] = { fg = M.base_30.orange },
    ["@function"] = { fg = M.base_16.base0D },
    ["@function.builtin"] = { fg = M.base_30.cyan },
    ["@function.call"] = { fg = M.base_16.base0D },
    ["@function.method"] = { fg = M.base_16.base0D },
    ["@function.method.call"] = { fg = M.base_16.base0D },
    ["@keyword"] = { fg = M.base_16.base0E },
    ["@keyword.function"] = { fg = M.base_16.base0E },
    ["@keyword.return"] = { fg = M.base_16.base0E },
    ["@keyword.operator"] = { fg = M.base_16.base0E },
    ["@operator"] = { fg = M.base_30.grey_fg2 },
    ["@punctuation.bracket"] = { fg = M.base_30.grey_fg2 },
    ["@punctuation.delimiter"] = { fg = M.base_30.grey_fg2 },
    ["@type"] = { fg = M.base_16.base0A },
    ["@type.builtin"] = { fg = M.base_16.base0A },
    ["@tag"] = { fg = M.base_30.red },
    ["@tag.attribute"] = { fg = M.base_30.orange },
    ["@tag.delimiter"] = { fg = M.base_30.grey_fg2 },
    ["@comment"] = { fg = M.base_30.grey, italic = true },
    ["@markup.heading"] = { fg = M.base_30.orange, bold = true },
    ["@markup.link"] = { fg = M.base_30.blue, underline = true },
    ["@markup.list"] = { fg = M.base_30.orange },
  },

  defaults = {
    Normal = { fg = M.base_16.base05, bg = M.base_16.base00 },
    NormalNC = { fg = M.base_16.base05, bg = M.base_16.base00 },
    NormalFloat = { fg = M.base_16.base05, bg = M.base_30.one_bg },
    FloatBorder = { fg = M.base_30.orange, bg = M.base_30.one_bg },
    FloatTitle = { fg = M.base_30.orange, bg = M.base_30.one_bg, bold = true },
    CursorLine = { bg = M.base_30.one_bg },
    CursorLineNr = { fg = M.base_30.orange, bold = true },
    LineNr = { fg = M.base_30.grey },
    Visual = { bg = "#2a2a2a" },
    Search = { fg = M.base_16.base00, bg = M.base_16.base0A },
    IncSearch = { fg = M.base_16.base00, bg = M.base_30.orange },
    CurSearch = { fg = M.base_16.base00, bg = M.base_30.orange },
    Pmenu = { fg = M.base_16.base05, bg = M.base_30.one_bg },
    PmenuSel = { fg = M.base_16.base00, bg = M.base_30.orange },
    PmenuSbar = { bg = M.base_30.one_bg2 },
    PmenuThumb = { bg = M.base_30.grey },
    MatchParen = { fg = M.base_30.orange, bold = true, underline = true },
    Comment = { fg = M.base_30.grey, italic = true },
    Constant = { fg = M.base_30.orange },
    String = { fg = M.base_30.green },
    Function = { fg = M.base_16.base0D },
    Keyword = { fg = M.base_16.base0E },
    Statement = { fg = M.base_16.base0E },
    Type = { fg = M.base_16.base0A },
    Special = { fg = M.base_30.orange },
    Identifier = { fg = M.base_16.base05 },
    Todo = { fg = M.base_16.base00, bg = M.base_30.orange, bold = true },
    Error = { fg = M.base_30.red },
    ErrorMsg = { fg = M.base_30.red },
    WarningMsg = { fg = M.base_30.yellow },
    DiagnosticError = { fg = M.base_30.red },
    DiagnosticWarn = { fg = M.base_30.yellow },
    DiagnosticInfo = { fg = M.base_30.blue },
    DiagnosticHint = { fg = M.base_30.cyan },
    DiagnosticVirtualTextError = { fg = "#ff6b6b", bg = "#1a1212" },
    DiagnosticVirtualTextWarn = { fg = "#fcc419", bg = "#1a1812" },
    DiagnosticVirtualTextInfo = { fg = "#4dabf7", bg = "#12151a" },
    DiagnosticVirtualTextHint = { fg = "#20c997", bg = "#121a17" },
    DiffAdd = { fg = M.base_30.green },
    DiffChange = { fg = M.base_30.yellow },
    DiffDelete = { fg = M.base_30.red },
    GitSignsAdd = { fg = M.base_30.green },
    GitSignsChange = { fg = M.base_30.yellow },
    GitSignsDelete = { fg = M.base_30.red },
    WinSeparator = { fg = M.base_30.one_bg2 },
    VertSplit = { fg = M.base_30.one_bg2 },
    StatusLine = { fg = M.base_16.base05, bg = M.base_30.statusline_bg },
    TabLine = { fg = M.base_30.grey_fg, bg = M.base_30.one_bg },
    TabLineFill = { bg = M.base_30.black },
    TabLineSel = { fg = M.base_16.base05, bg = M.base_30.one_bg2 },
    TelescopePromptBorder = { fg = M.base_30.orange },
    TelescopeResultsBorder = { fg = M.base_30.one_bg2 },
    TelescopePreviewBorder = { fg = M.base_30.one_bg2 },
    TelescopePromptTitle = { fg = M.base_30.black, bg = M.base_30.orange, bold = true },
    TelescopeResultsTitle = { fg = M.base_30.one_bg2 },
    TelescopePreviewTitle = { fg = M.base_30.black, bg = M.base_30.green, bold = true },
    TelescopeSelection = { bg = M.base_30.one_bg2 },
    NvimTreeNormal = { fg = M.base_16.base05, bg = M.base_30.darker_black },
    NvimTreeNormalNC = { fg = M.base_16.base05, bg = M.base_30.darker_black },
    NvimTreeWinSeparator = { fg = M.base_30.darker_black, bg = M.base_30.darker_black },
    NvimTreeFolderIcon = { fg = M.base_30.orange },
    NvimTreeFolderName = { fg = M.base_30.blue },
    NvimTreeOpenedFolderName = { fg = M.base_30.blue, bold = true },
    NvimTreeRootFolder = { fg = M.base_30.orange, bold = true },
    FlashLabel = { fg = M.base_30.black, bg = M.base_30.orange, bold = true },
    FlashCurrent = { fg = M.base_30.black, bg = M.base_30.yellow },
    FlashMatch = { fg = M.base_30.orange },
    DapBreakpoint = { fg = M.base_30.red },
    DapBreakpointCondition = { fg = M.base_30.yellow },
    DapLogPoint = { fg = M.base_30.cyan },
    DapStopped = { fg = M.base_30.green },
    DapStoppedLine = { bg = "#1a2a1a" },
    DapBreakpointRejected = { fg = M.base_30.grey },
  },
}

M.type = "dark"

return M
